server:
  port: 8082
  servlet:
    context-path: /app
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: vehicle-service
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/microservice_vehicle?createDatabaseIfNotExist=true

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl